<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-calibre-net-460c1009-5615-4b82-a0fa-faab7c79bf67</UserSecretsId>
    <RootNamespace>Calibre-net</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Data\app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.FluentValidation" Version="2.1.0" />
    <PackageReference Include="CodeBeam.MudBlazor.Extensions" Version="6.9.2" />
    <PackageReference Include="dapper" Version="2.1.35" />
    <PackageReference Include="FastEndpoints" Version="5.35.0" />
    <PackageReference Include="FastEndpoints.Security" Version="5.35.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="5.35.0" />
    <PackageReference Include="Fido2" Version="4.0.0-beta.16" />
    <PackageReference Include="Fido2.AspNet" Version="4.0.0-beta.16" />
    <PackageReference Include="FluentResults" Version="3.16.0" />
    <PackageReference Include="HeimGuard" Version="1.0.0" />
    <PackageReference Include="InterpolatedSql.Dapper" Version="2.3.0" />
    <PackageReference Include="Markdig" Version="0.37.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.*" />
    <PackageReference Include="Riok.Mapperly" Version="3.5.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="VersOne.Epub" Version="3.3.1" />
    <PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="9.103.7.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="z440.atl.core" Version="5.22.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\aaguid.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Calibre-net.Client\Calibre-net.Client.csproj" />
    <ProjectReference Include="..\Calibre-net.Shared\Calibre-net.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ComicMeta" Version="1.0.8" />
    <!-- <ProjectReference Include="..\..\Components\ComicMeta\ComicMeta.csproj" />  -->
  </ItemGroup>

  <!-- <ItemGroup Condition=" '$(Configuration)'!='Debug' ">
    <PackageReference Include="ComicMeta" Version="1.0.6" />
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)'=='Debug' ">
    <ProjectReference Include="..\..\Components\ComicMeta\ComicMeta.csproj" /> 
  </ItemGroup> -->
  
  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="6.5.1">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

<!-- <PropertyGroup>
  <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
</PropertyGroup> -->

</Project>
