name: Publish to server

# Controls when the workflow will run
on:
  # Triggers the workflow on push request event for the dev or master branch
  push:    
    branches: [dev, main]
    tags: ['v*']

jobs:
  deploy:
    # Our previously created self-hosted runner
    runs-on: self-hosted

    strategy:
      matrix:
        dotnet: ["9.0.x"]

    # A sequence of tasks that will execute as part of the job
    steps:
      # Checks out repository so our job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0' #for GitVersion
      - name: Setup .NET ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
        
      - name: Setup .NET wasm-tools
        run: sudo dotnet workload install wasm-tools
        continue-on-error: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        # run: dotnet build --configuration Release --no-restore
        run: dotnet build --configuration Release --no-restore
        #--no-restore

      - name: Install EF Core CLI
        run: dotnet tool update dotnet-ef --global 
        shell: bash
      # - name: Install Ef tooling
      #   run: |
      #     dotnet tool update --global dotnet-ef
      #     dotnet tool restore
      - name: Generate efbundle for Migrations
        run: ~/.dotnet/tools/dotnet-ef migrations bundle --configuration Release --no-build -p ./Calibre-net -c ApplicationDbContext --self-contained

      # We will output publish files to the folder we previously created
      - name: Publish
        run: dotnet publish Calibre-net -c Release -o /opt/calibre-net

      - name: Restart the app
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart calibre-net.service